# Snippet 1

In [2]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [14]:
# Dimensions of the Matrix with the array
b=np.random.randn(5,1)
print(b.shape)
print(b)
# how to transpose the Matrix
print(b.T)
print(np.dot(b,b.T))


(5, 1)
[[ 0.35435883]
 [ 0.53314408]
 [ 0.27202247]
 [ 0.22372184]
 [-0.47670645]]
[[ 0.35435883  0.53314408  0.27202247  0.22372184 -0.47670645]]
[[ 0.12557018  0.18892431  0.09639356  0.07927781 -0.16892514]
 [ 0.18892431  0.28424261  0.14502717  0.11927597 -0.25415322]
 [ 0.09639356  0.14502717  0.07399622  0.06085737 -0.12967486]
 [ 0.07927781  0.11927597  0.06085737  0.05005146 -0.10664964]
 [-0.16892514 -0.25415322 -0.12967486 -0.10664964  0.22724904]]


# Vectors vs Normal Product

In [4]:
#vectors
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print("Vectorised"+ str(1000*(toc-tic))+"ms")


Vectorised28.946399688720703ms


In [5]:
c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print("Vectorised"+ str(1000*(toc-tic))+"ms")

Vectorised968.2588577270508ms


- Vectorised Version runs min of 200x faster