# Vectorization in Numpy

In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [6]:
# Dimensions of the Matrix with the array
b=np.random.randn(5,1)
print(b.shape)
print(b)
# how to transpose the Matrix
print(b.T)
print(np.dot(b,b.T))


(5, 1)
[[0.43143226]
 [0.42236275]
 [0.0061611 ]
 [0.56723898]
 [1.98961948]]
[[0.43143226 0.42236275 0.0061611  0.56723898 1.98961948]]
[[1.86133799e-01 1.82220918e-01 2.65809545e-03 2.44725197e-01
  8.58386038e-01]
 [1.82220918e-01 1.78390294e-01 2.60221732e-03 2.39580615e-01
  8.40341158e-01]
 [2.65809545e-03 2.60221732e-03 3.79590997e-05 3.49481360e-03
  1.22582359e-02]
 [2.44725197e-01 2.39580615e-01 3.49481360e-03 3.21760058e-01
  1.12858972e+00]
 [8.58386038e-01 8.40341158e-01 1.22582359e-02 1.12858972e+00
  3.95858567e+00]]


# Vectors vs Normal Product

In [7]:
#vectors
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print("Vectorised"+ str(1000*(toc-tic))+"ms")


Vectorised29.071331024169922ms


In [8]:
c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print("Vectorised"+ str(1000*(toc-tic))+"ms")

Vectorised781.517505645752ms


- Vectorised Version runs min of 200x faster

# Performance Comparison - Dot , Outer , Multiply 

In [9]:
import time
import numpy as np

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot = 278
 ----- Computation time = 0.29246500000024156ms


In [10]:
### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 ----- Computation time = 0.5515970000002923ms

In [11]:
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

elementwise multiplication = [81.  4. 10.  0.  0. 63. 10.  0.  0.  0. 81.  4. 25.  0.  0.]
 ----- Computation time = 0.31288600000012323ms


In [12]:
### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

gdot = [14.07616542 24.81175246 25.7999057 ]
 ----- Computation time = 0.4298889999998501ms


# Now same thing in Vectorization

In [15]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
#Multiply corresponding numbers and add them all
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print("\n")
print("\n VECTORIZED DOT PRODUCT OF VECTORS")


dot = 278
 ----- Computation time = 0.1388529999997168ms



 VECTORIZED DOT PRODUCT OF VECTORS


![Vector outer product](https://wikimedia.org/api/rest_v1/media/math/render/svg/c2c4d3a02ef963f9d1bde06ac67abee9e3204475)


In [ ]:
### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print("\n")
print("\n VECTORIZED OUTER PRODUCT")


### VECTORIZED ELEMENTWISE MULTIPLICATION ###
#multiply each element to its corresponding element
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print("\n")
print("\n VECTORIZED ELEMENTWISE MULTIPLICATION")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print("\n")
print("\nVECTORIZED GENERAL DOT PRODUCT  ")