In [2]:
import numpy as np
A=np.array([[56.0,0.0,4.4,68.0],
          [1.2,104.0,52.0,8.0],
          [1.8,135.0,99.0,0.9]])
print(A)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
# sum the elements of the column vertically
cal=A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [12]:
percentage=100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [4]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
print(a.shape)
b = np.random.randn(2, 1) # b.shape = (2, 1)
print(b.shape)
# output Gets max Dimension
c = a + b
print(c.shape)

(2, 3)
(2, 1)
(2, 3)


In [11]:
a = np.random.randn(4,3)
print(a.shape)
b = np.random.randn(3,4)
print(b.shape)
#Multiplication require same dimension 
c = a * b
print(c.shape)

(4, 3)
(3, 4)


ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [7]:
a = np.random.randn(4,3)
print(a.shape)
b = np.random.randn(3,2)
print(b.shape)
#Dot Product gives MN 
c = np.dot(a,b)
print(c.shape)

(4, 3)
(3, 2)
(4, 2)


In [8]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c.shape)


(3, 3)
